### ISSUE TITLE
cv2.error:......The input arrays should have at least 4 corresp onding point sets to calculate Homography in function 'cv::findHomography'

### ISSUE THREAD

**Issue by fppccc** [Chen-Zehao12/ImageStitching#1]
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\fundam.cpp:385: error: (-28:Unknown error code -28) The input arrays should have at least 4 corresponding point sets to calculate Homography in function 'cv::findHomography'
How could I solve this problem?Thank you very much.
是因为我的图片不足以找到四个对应点吗？感谢！！

**Comment by CodingMonkey12** [comment]
Yes, there is a sentence in OpenCV: We need at least 4 corresponding points. Maybe you should change pictures.🤔
从报错里来看的话确实是这样的。在OpenCV中是这么说的：我们需要至少4个对应的点。可能得换换图片了。🤔

**Comment by fppccc** [comment]
> Yes, there is a sentence in OpenCV: We need at least 4 corresponding points. Maybe you should change pictures.🤔 从报错里来看的话确实是这样的。在OpenCV中是这么说的：我们需要至少4个对应的点。可能得换换图片了。🤔

感谢！！！
